<a href="https://colab.research.google.com/github/k-v-n-p/mwd/blob/main/Aks_FINAL_PHASE_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##PREPROCESSING

In [9]:
from google.colab import drive
drive.mount('/content/drive',force_remount=True)

Mounted at /content/drive


In [10]:

import pandas as pd
from ast import literal_eval
#def load_even_numbered_images():
#for akshata
# df=pd.read_csv('/content/drive/MyDrive/ Multimedia webD-group 18/phase-1 csv output/Phase1_output_final.csv')
#for pranav
df=pd.read_csv('/content/drive/MyDrive/Phase1_output_final.csv')
# #  df=df.dropna()

In [11]:
from torchvision.datasets import Caltech101
from torch.utils.data import DataLoader
#caltech101_dataset = Caltech101(root='./data', download=True)
# caltech101_dataset = Caltech101(root='./content/drive/MyDrive/caltech-101', download=True)

#####Literal eval ondata

In [12]:
df['Feature Vector CM'] = df['Feature Vector CM'].apply(literal_eval)
df['Feature Vector HOG'] = df['Feature Vector HOG'].apply(literal_eval)
df['Feature Vector Resnet50 AvgPool'] = df['Feature Vector Resnet50 AvgPool'].apply(literal_eval)
df['Feature Vector Resnet50 Layer3'] = df['Feature Vector Resnet50 Layer3'].apply(literal_eval)
df['Feature Vector Resnet50 FC'] = df['Feature Vector Resnet50 FC'].apply(literal_eval)

#####EVEN NUMBERED DATA

In [13]:
training_df = df[df['ImageID'] % 2 == 0]
training_df

ImageID  Image Label                                  Feature Vector CM  \
0         0.0            0  [100.69666666666667, 42.527222523409115, 82.04...   
2         2.0            0  [234.06666666666666, 29.421911713702237, -91.2...   
4         4.0            0  [102.15666666666667, 21.147232810832616, -69.9...   
6         6.0            0  [205.21, 20.449920130243378, -82.1055325418300...   
8         8.0            0  [153.56666666666666, 5.854817579471533, -24.15...   
...       ...          ...                                                ...   
8668   8668.0          100  [1.0, 0.0, 0.0, 3.0, 0.0, 0.0, 2.0, 0.0, 0.0, ...   
8670   8670.0          100  [252.0, 0.0, 0.0, 84.0, 0.0, 0.0, 84.0, 0.0, 0...   
8672   8672.0          100  [102.0, 0.0, 0.0, 255.0, 0.0, 0.0, 102.0, 0.0,...   
8674   8674.0          100  [175.58666666666667, 16.31223944023492, -33.60...   
8676   8676.0          100  [254.0, 0.0, 0.0, 254.0, 0.0, 0.0, 254.0, 0.0,...   

                                     Feature Vector HOG  \
0     [1525.7460257360444, 2054.6132694859325, 3816....   
2     [52.29822128134704, 880.471281897526, 433.1304...   
4     [617.6338272474198, 4.0, 772.4635366228489, 14...   
6     [325.2436315986929, 682.0480148728668, 243.681...   
8     [35.39834563766817, 1284.4654539960177, 23.0, ...   
...                                                 ...   
8668  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
8670  [0.0, 3.0, 517.95271812803, 100.28830285560615...   
8672  [0.0, 0.0, 91.20809626481889, 698.213923032411...   
8674  [1291.7874597623174, 1099.9162504042056, 1026....   
8676  [0.0, 0.0, 0.0, 55.0, 498.44030650891057, 40.0...   

                        Feature Vector Resnet50 AvgPool  \
0     [0.38452914357185364, 0.22774668037891388, 0.5...   
2     [0.6112032532691956, 0.06909624487161636, 0.38...   
4     [0.47124505043029785, 0.17865031957626343, 0.6...   
6     [0.2692595422267914, 0.1840372085571289, 0.548...   
8     [0.473470538854599, 0.22144927084445953, 0.343...   
...                                                 ...   
8668  [0.07785946130752563, 0.20540767908096313, 0.4...   
8670  [0.28768500685691833, 0.021389015018939972, 0....   
8672  [0.7721341252326965, 0.018516598269343376, 0.5...   
8674  [0.2209039330482483, 0.12189736217260361, 0.20...   
8676  [0.18081176280975342, 0.03819337114691734, 0.6...   

                         Feature Vector Resnet50 Layer3  \
0     [0.0916738286614418, 0.011883005499839783, 0.0...   
2     [0.06605225056409836, 0.008654458448290825, 0....   
4     [0.0752222016453743, 0.011122970841825008, 0.0...   
6     [0.06716498732566833, 0.0007487232214771211, 0...   
8     [0.093476302921772, 0.007879584096372128, 0.01...   
...                                                 ...   
8668  [0.08441931754350662, 0.015729054808616638, 0....   
8670  [0.06998571753501892, 0.05664614588022232, 0.0...   
8672  [0.0395333394408226, 0.047223374247550964, 0.0...   
8674  [0.06758628785610199, 0.019224446266889572, 0....   
8676  [0.06360840052366257, 0.041659146547317505, 0....   

                             Feature Vector Resnet50 FC  
0     [1.7503321170806885, -0.36116427183151245, 1.9...  
2     [7.684633255004883, 1.0451585054397583, -0.021...  
4     [3.5299644470214844, 0.4599866569042206, 1.409...  
6     [1.7933485507965088, 0.8007387518882751, 1.105...  
8     [6.201627731323242, 1.967166781425476, 1.37596...  
...                                                 ...  
8668  [-2.914402484893799, 0.2537955343723297, -1.29...  
8670  [-0.3573322296142578, 1.3825989961624146, -2.3...  
8672  [-1.407240390777588, 0.37475642561912537, -1.9...  
8674  [0.26897168159484863, 1.7014539241790771, -1.6...  
8676  [-1.4049566984176636, 0.5445044040679932, -2.2...  

[4339 rows x 7 columns]

#####ODD NUMBERED DATA

In [14]:
query_df = df[df['ImageID'] % 2 != 0]

#####DF FOR TASK 4

In [15]:
import ast
df_task4 = df1.drop(columns=['ImageID', 'Image Label'])

# Convert string representations of lists to actual lists
#df_task4['Feature Vector Resnet50 AvgPool'] = df_task4['Feature Vector Resnet50 AvgPool'].apply(ast.literal_eval)

# Ensure that all values in the DataFrame are floats
df_task4= df_task4.applymap(lambda x: [float(y) for y in x] if isinstance(x, list) else float(x))

# Print the resulting DataFrame
df_task4

NameError: ignored

## PROJECT TASKS


###TASK 0

####0A

In [ ]:
import numpy as np
import pandas as pd

# Assuming your data is stored in a DataFrame called df

# Convert each elemewnt in the DataFrame to float64
def TASK0A(threshold):
    # Extract feature vectors for even-numbered images
    even_image_feature_vectors = np.vstack(training_df['Feature Vector Resnet50 AvgPool'])
    # Compute the covariance matrix
    mean_centered_data = even_image_feature_vectors - np.mean(even_image_feature_vectors, axis=0)
    covariance_matrix = np.dot(mean_centered_data.T, mean_centered_data) / (even_image_feature_vectors.shape[0] - 1)
    # Perform PCA using eigendecomposition
    eigenvalues, eigenvectors = np.linalg.eigh(covariance_matrix)
    eigenvectors = eigenvectors[:, ::-1]  # Sort in descending order
    # Compute inherent dimensionality (e.g., using a threshold)
    cumulative_variance = np.cumsum(eigenvalues) / np.sum(eigenvalues)
    # print('cumulative_variance ',cumulative_variance)
    # print('np.cumsum(cumulative_variance) ',np.cumsum(cumulative_variance))
    inherent_dimensionality = np.argmax(np.cumsum(cumulative_variance) >= threshold) + 1

    print("Inherent Dimensionality for Even Numbered Images:", inherent_dimensionality)


In [ ]:
threshold=float(input('ENTER THRESHOLD ')) #explain at least 95% of the total variance.
TASK0A(threshold)

ENTER THRESHOLD 0.6
cumulative_variance  [8.44049637e-06 1.72902344e-05 2.62651616e-05 ... 8.62954931e-01
 9.24030390e-01 1.00000000e+00]
np.cumsum(cumulative_variance)  [8.44049637e-06 2.57307308e-05 5.19958923e-05 ... 5.40444016e+01
 5.49684320e+01 5.59684320e+01]
Inherent Dimensionality for Even Numbered Images: 280


####0B

In [ ]:
def TASK0B(threshold):
  unique_labels = df['Image Label'].unique()

  for label in unique_labels:
      # Extract feature vectors for even-numbered images with the current label and convert to float64
      even_image_feature_vectors_label = np.vstack(training_df['Feature Vector Resnet50 AvgPool'].loc[training_df['Image Label'] == label])
     # print('Label: ', label,(df1['Feature Vector Resnet50 AvgPool'].loc[df1['Image Label'] == label]))
      # Compute PCA for the current label
      mean_centered_data_label = even_image_feature_vectors_label - np.mean(even_image_feature_vectors_label, axis=0)
      #print('mean_centered_data_label ',mean_centered_data_label, '\n')
      covariance_matrix_label = np.dot(mean_centered_data_label.T, mean_centered_data_label) / (even_image_feature_vectors_label.shape[0] - 1)
      #print('covariance_matrix_label ',covariance_matrix_label,'\n')
      eigenvalues_label, eigenvectors_label = np.linalg.eigh(covariance_matrix_label)
      eigenvectors_label = eigenvectors_label[:, ::-1]  # Sort in descending order
      #print('eigenvalues_label ',eigenvalues_label,'\n')
      #print('eigenvectors_label ',eigenvectors_label,'\n')
      # Compute inherent dimensionality for the current label
      cumulative_variance_label = np.cumsum(eigenvalues_label) / np.sum(eigenvalues_label)
      inherent_dimensionality_label = np.argmax(cumulative_variance_label >= threshold) + 1
      #print('cumulative_variance_label ',cumulative_variance_label,'\n')


      print(f"Inherent Dimensionality for Label {label}: {inherent_dimensionality_label}")


In [ ]:
threshold=float(input('ENTER THRESHOLD ')) #explain at least 95% of the total variance.
TASK0B(threshold)

###TASK 1

In [ ]:
import numpy as np

def compute_latent_semantics(data, k):
    # Extract even numbered images and their feature vectors
    even_data = data

    # Group data by label
    grouped_data = even_data.groupby('Image Label')

    # Dictionary to store latent semantics for each label
    latent_semantics_dict = {}

    for label, group in grouped_data:
        # Extract feature vectors for the current label
      #  print('Label: ',label,'\ngroup: ', group)
        feature_vectors = np.array(group['Feature Vector Resnet50 AvgPool'].tolist())

        # Center the data (subtract mean)
        mean_vector = np.mean(feature_vectors, axis=0)
        centered_data = feature_vectors - mean_vector

        # Calculate the covariance matrix
        covariance_matrix = np.cov(centered_data, rowvar=False)

        # Compute eigenvalues and eigenvectors
        eigenvalues, eigenvectors = np.linalg.eigh(covariance_matrix)

        # Sort eigenvalues and corresponding eigenvectors in descending order
        idx = np.argsort(eigenvalues)[::-1]
        eigenvalues = eigenvalues[idx]
        eigenvectors = eigenvectors[:, idx]

        # Take the top k eigenvectors to form the latent semantics
        latent_semantics = eigenvectors[:, :k]

        # Store the latent semantics for the current label
        latent_semantics_dict[label] = latent_semantics

        # Print k latent semantics for each label
        print(f'Label: {label}, Latent Semantics:')
        print(latent_semantics)
        print('---')

    return latent_semantics_dict


def predict_labels(query_data, latent_semantics_dict):
    # Dictionary to store predictions for each label
    predictions_dict = {'True Label': [], 'Predicted Label': []}

    for index, row in query_data.iterrows():
        # Extract relevant information
        true_label = row['Image Label']
        feature_vector = np.array(row['Feature Vector Resnet50 AvgPool'])

        # Find the label-specific latent semantics
        latent_semantics = latent_semantics_dict.get(true_label, None)

        if latent_semantics is not None:
            # Project the feature vector onto the label-specific latent semantics
            projection = np.dot(latent_semantics.T, feature_vector)

            # Find the label with the closest projection
            predicted_label = min(latent_semantics_dict.keys(),
                                  key=lambda label: np.linalg.norm(projection - np.dot(latent_semantics_dict[label].T, feature_vector)))
            print('predicted label for image',index, ':' ,predicted_label)

            # Store predictions
            predictions_dict['True Label'].append(true_label)
            predictions_dict['Predicted Label'].append(predicted_label)

    return predictions_dict



def evaluate(predictions_dict):
    # Convert predictions to a DataFrame
    predictions_df = pd.DataFrame(predictions_dict)

    # Calculate overall accuracy
    overall_accuracy = (predictions_df['True Label'] == predictions_df['Predicted Label']).mean()

    # Calculate per-label precision, recall, and F1-score
    per_label_metrics = {}
    unique_labels = predictions_df['True Label'].unique()

    for label in unique_labels:
        true_positives = ((predictions_df['True Label'] == label) & (predictions_df['Predicted Label'] == label)).sum()
        false_positives = ((predictions_df['True Label'] != label) & (predictions_df['Predicted Label'] == label)).sum()
        false_negatives = ((predictions_df['True Label'] == label) & (predictions_df['Predicted Label'] != label)).sum()

        precision = true_positives / (true_positives + false_positives)
        recall = true_positives / (true_positives + false_negatives)
        f1_score = 2 * (precision * recall) / (precision + recall)

        per_label_metrics[label] = {'Precision': precision, 'Recall': recall, 'F1-Score': f1_score}

    return overall_accuracy, per_label_metrics


###TASK 4

####TASK 4A

In [ ]:
import numpy as np
import pandas as pd

def hash_vector(vector, layer):
    np.random.seed(layer)
    return hash(tuple(vector + [layer]))

def build_index(num_layers, vectors_df):
    index = {}

    for layer in range(num_layers):
        hashes = []
        for _, row in vectors_df.iterrows():
            vector = row['Feature Vector Resnet50 AvgPool']  # Change this according to your chosen visual model
            hash_value = hash_vector(vector, layer)
            hashes.append(hash_value)

        index[layer] = hashes

    return index

def print_index(index):
    for layer, hashes in index.items():
        print(f"Layer {layer + 1} Hashes: {hashes}")

def main():
    # Example usage
    # Assuming df is your dataframe containing the vectors
    # Change the column name for the feature vector based on your model
    df = training_df  # Replace 'your_dataframe.csv' with the actual file path
    num_layers = 3

    index = build_index(num_layers, df)
    print_index(index)

main()


In [ ]:
import numpy as np
from itertools import combinations

def generate_lsh(num_layers, num_hashes, dimensions):
    tables = [{} for _ in range(num_layers)]

    # Generate random hash functions for each layer
    hash_functions = np.random.randn(num_layers, num_hashes, dimensions)

    def hash_vector(vector):
        hash_values = np.dot(hash_functions, vector)
        return (hash_values >= 0).astype(int)

    def index_vector(vector, index):
        hash_values = hash_vector(vector)
        for i, h in enumerate(hash_values):
            hash_key = tuple(h)
            if hash_key not in tables[i]:
                tables[i][hash_key] = []
            tables[i][hash_key].append(index)

    def build_index(vectors):
        for i, vector in enumerate(vectors):
            index_vector(vector, i)

    def query(query_vector, threshold=0.1):
        query_hash = hash_vector(query_vector)
        candidate_indices = set()

        for i, h in enumerate(query_hash):
            hash_key = tuple(h)
            if hash_key in tables[i]:
                candidate_indices.update(tables[i][hash_key])

        # Compute actual distances and filter by threshold
        candidates = [(idx, np.linalg.norm(query_vector - vectors[idx]))
                      for idx in candidate_indices]

        return sorted(candidates, key=lambda x: x[1])[:10]  # Return top 10

    return hash_vector, index_vector, build_index, query

# Example Usage:
# Create LSH index with 2 layers, 4 hashes per layer, and vectors of dimension 256
num_layers = 2
num_hashes = 4
dimensions = 256
hash_vector, index_vector, build_index, query = generate_lsh(num_layers, num_hashes, dimensions)

# Generate random vectors for testing
num_vectors = 1000
vector_dimensions = 256
vectors = np.random.rand(num_vectors, vector_dimensions)
print("vectors first \n len \n", vectors[0],"\n",len(vectors))

# Build the LSH index
build_index(vectors)

# Query a random vector and get similar vectors
query_vector = np.random.rand(vector_dimensions)
similar_vectors = query(query_vector)

print("Similar Vectors:")
for idx, distance in similar_vectors:
    print(f"Index: {idx}, Distance: {distance}")


####TASK 4B

In [ ]:
import matplotlib.pyplot as plt
import matplotlib.image as mpimg

class ImageSearch:
    def __init__(self, lsh, query_vector, t):
        self.lsh = lsh
        self.query_vector = query_vector
        self.t = t

    def search_images(self):
        unique_images = set()
        all_images = set()

        distances = []
        for layer, hashes in self.lsh.index.items():
            hash_value = self.lsh.hash_vector(self.query_vector, layer)
            hash_value = np.array([hash_value]).reshape(1, -1)
            layer_distances = euclidean_distances(hash_value, np.array(hashes).reshape(-1, 1)).flatten()
            distances.extend(layer_distances)

        sorted_indices = np.argsort(distances)
        top_indices = sorted_indices[:self.t]
        print(top_indices)
        print(sorted_indices)
        for idx in top_indices:
            if idx < len(self.lsh.vectors_df):
                print(' len(self.lsh.vectors_df', len(self.lsh.vectors_df))
                print(idx)
                image_id = self.lsh.vectors_df.iloc[idx]['ImageID']
                print('image_id',image_id)
                unique_images.add(image_id)
                all_images.add(image_id)
                self.display_image(image_id)

        return list(unique_images), list(all_images)

    def display_image(self, image_id):
        # Load and display the image using its file path or URL
        # Replace 'image_file_path' with the actual path or URL of your images
        img = caltech101_dataset[int(image_id)][0]
        # img = mpimg.imread(image_file_path)
        plt.imshow(img)
        plt.axis('off')
        plt.show()

# Example usage
# Assuming query_vector is the feature vector of the query image
# Change the column name for the feature vector based on your model
image_id=881
query_vector = df1.loc[df1['ImageID'] == image_id]['Feature Vector Resnet50 AvgPool']
t = 10

image_search = ImageSearch(lsh, query_vector, t)
unique_images, all_images = image_search.search_images()

print(f"Unique Images: {unique_images}")
print(f"Overall Number of Images Considered: {len(all_images)}")


###QUERY INPUTS:

Task 1:

k = 5

Task 2:

c=5, 10

Task 3:

m=1,5,10

PPR random jump probability = 0.15, 0.5

Task 4:

L=3,10

h=3,10

t=10

Query images: {1, 881, 2501, 5123, 8675}

##Interfaces


###Task 0


#### 0A

In [ ]:
threshold=float(input('ENTER THRESHOLD ')) #explain at least 95% of the total variance.
TASK0A(threshold)# no input just inherent dimensionality associated wit even numbered caltech 101 images

ENTER THRESHOLD 0.95
Inherent Dimensionality for Even Numbered Images: 338


#### 0B

In [ ]:
threshold=float(input('ENTER THRESHOLD ')) #explain at least 95% of the total variance.
TASK0B(threshold) # no input just inherent dimensionality associated with each unique label of even numbered caltech 101 images

ENTER THRESHOLD 0.8
Inherent Dimensionality for Label 0: 1023
Inherent Dimensionality for Label 1: 1023
Inherent Dimensionality for Label 2: 1023
Inherent Dimensionality for Label 3: 1023
Inherent Dimensionality for Label 4: 1023
Inherent Dimensionality for Label 5: 1023
Inherent Dimensionality for Label 6: 1023
Inherent Dimensionality for Label 7: 1023
Inherent Dimensionality for Label 8: 1023
Inherent Dimensionality for Label 9: 1023
Inherent Dimensionality for Label 10: 1023
Inherent Dimensionality for Label 11: 1023
Inherent Dimensionality for Label 12: 1023
Inherent Dimensionality for Label 13: 1023
Inherent Dimensionality for Label 14: 1023
Inherent Dimensionality for Label 15: 1023
Inherent Dimensionality for Label 16: 1023
Inherent Dimensionality for Label 17: 1023
Inherent Dimensionality for Label 18: 1024
Inherent Dimensionality for Label 19: 1023
Inherent Dimensionality for Label 20: 1024
Inherent Dimensionality for Label 21: 1023
Inherent Dimensionality for Label 22: 1023
I

### Task 1


In [ ]:
# input:  k, query image
# output: (even) k latent semantics,  (any method, feature space)
#         (odd) most likely labels from label-specific latent semantics (check for 0b usage?)
# Other outputs: per-label precision, recall and F1-score, overall accuracy

# Set the value of k for the number of latent semantics
k = int(input('ENTER THE VALUE OF K '))

# Step 1: Compute k latent semantics for each label using even numbered images
latent_semantics_dict = compute_latent_semantics(training_df, k)

# Step 2: Predict labels for odd numbered images using label-specific latent semantics
predictions_dict = predict_labels(query_df, latent_semantics_dict)
# print('PREDICTIONs:')
# print()
# for i in range(len(predictions_dict['True Label'])):
#     print('True Label for image', i , ' :', predictions_dict['True Label'][i])
#     print('Predicted Label for image ', i , ' :', predictions_dict['Predicted Label'][i])
#     print()
#     print('==================================')
#     print()


# # Step 3: Evaluate the predictions
# overall_accuracy, per_label_metrics =  evaluate(predictions_dict)

# # Step 4: Print the results
# print(f'Overall Accuracy: {overall_accuracy:.2%}')
# print('Per-Label Metrics:')
# for label, metrics in per_label_metrics.items():
#     print(f'Label {label}: Precision={metrics["Precision"]:.2%}, Recall={metrics["Recall"]:.2%}, F1-Score={metrics["F1-Score"]:.2%}')



Streaming output truncated to the last 5000 lines.
[[ 0.01838833 -0.07137363  0.04965881 -0.10088776  0.07628924]
 [ 0.00507398 -0.0107394   0.02273359  0.00142958 -0.04153523]
 [ 0.02778801  0.00724525  0.01229112  0.03766072  0.01147202]
 ...
 [-0.00450304 -0.01735418 -0.02881752 -0.00600817 -0.00394094]
 [ 0.00897312 -0.03934802  0.01754838 -0.01233198  0.00294039]
 [ 0.02071922 -0.00996841 -0.02145734 -0.00697056 -0.06515447]]
---
Label: 33, Latent Semantics:
[[ 0.02017698 -0.00975099  0.01862269 -0.02256368  0.02065478]
 [ 0.06212478 -0.02084948  0.00642076  0.0599364  -0.00830097]
 [ 0.02998465 -0.01429279  0.02047879 -0.08015931 -0.03087664]
 ...
 [-0.00177407 -0.00699474  0.0024591  -0.00368439  0.01264443]
 [ 0.012139   -0.03348437 -0.00120633 -0.00762152  0.00947903]
 [ 0.03661423  0.03085835  0.09703485 -0.00077594  0.03447481]]
---
Label: 34, Latent Semantics:
[[ 0.01694001 -0.01838407  0.00056069 -0.00099154  0.02708026]
 [-0.02243712 -0.02383585  0.02220217  0.01033104  0

### Task 2

In [ ]:
# input:
# output: *clusters visualized* as diffrently colored point clouds in MDS space, als0 as groups of image thumbnails,
#          (even) computes c most significant clusters
#          (odd) most likely labels using c label-specific clusters
# Other outputs: per-label precision, recall and F1-score, overall accuracy

###Task 3

In [ ]:
# input: Image input,
#        choice to choose from (1. m-NN classifier (user specified m),
#                               2. decision-tree classifier,
#                               3. PPR based classifier )
# output: (Even) creates the given classifier
#         (Odd) Most likely labels on the given classifier
# Other outputs: per-label precision, recall and F1-score, overall accuracy

###Task 4

#### 4a

In [ ]:
# output: in-memory index  structure containing the given set of vectors
num_layers=int(input('ENTER NUMBER OF LAYERS '))
num_hashes=int(input('ENTER NUMBER OF HASHES PER LAYER '))
feature_vectors=int(input('ENTER NUMBER OF HASHES PER LAYER ')) # or fron the df for any


####4b

In [ ]:
# output: t most similar images, number of unique and overall number of images considered during the process
# visual models? (a combined visual model of atleast 256 dimensions)
query_image=int(input('Enter the query image id '))
t=int(input('Number of similar Images required '))


### Task 5

In [ ]:
# input: query image, k-similar images(from 4b), user choice(SVM based, probabilistic relevance feedback system)
# output: tag results of k-similar in R+, R, I, I-
#         Returns a set of ranked results (revise the query or re-order existing results)
# Other outputs: per-label precision, recall and F1-score, overall accuracy